### ISSUE TITLE
Differentiate between mouse_diff and cursor_diff values

### ISSUE THREAD

**Issue by agorgl** [rukai/winit_input_helper#12]
Currently, your mouse_diff api depends WindowEvent::CursorMoved event. This is confusing as winit offers a DeviceEvent::MouseMotion event that shows whether the mouse has moved, in contrast with the WindowEvent::CursorMoved which shows whether the cursor has moved.

With this in mind, you should have 2 relevant functions: mouse_diff (that uses DeviceEvent::MouseMotion event) and cursor_diff (that uses WindowEvent::CursorMoved event). The first one will always trigger when moving the mouse, while the second one will trigger only the cursor moves. This will allow the users to build things like first person cameras that have a potential infinite mouse movement when grabing the cursor in the window.

This is not currently possible with the mouse_diff api, because even when grabing the cursor in the window, the cursor at some point reaches the window edge and it stops generating mouse diff events.

**Comment by TheButlah** [comment]
Created #37 which should close this.

**Comment by rukai** [comment]
Implemented in https://github.com/rukai/winit_input_helper/pull/37
