### ISSUE TITLE
Reexport winit features

### ISSUE THREAD

**Issue by anisse** [rukai/winit_input_helper#21]
It's often desirable to reduce the winit feature set depending on your platform and needs, and it can reduce the binary size. But to using winit_input_helper negates that since it uses the default feature set. By re-exporting the features, it should be possible to only keep one winit version in the binaries.

**Comment by rukai** [comment]
Thanks, thats a good observation!
I've gone ahead and made the change.

It is however a breaking change so I'll need to release it in a `0.x.y` release.
Seeing as the only concern is decreased binary size and compile time, I think i'll wait until the next winit release to do another winit_input_helper release.
