### ISSUE TITLE
Cancel quit?

### ISSUE THREAD

**Issue by parasyte** [rukai/winit_input_helper#24]
When the `quit` boolean is set to true, it is permanently true. Since it can't be reset, I'm not able to use it for close requests.

I want to prompt the user to confirm the close request when there is unsaved progress. It's a game, but you do see the same UX expectation with many applications.

There is also an issue with not being able to tell the difference between a close request and the window getting destroyed: https://github.com/rukai/winit_input_helper/blob/197eaa3f1c8c0f691c80f59ff9369e0568a819ce/src/winit_input_helper.rs#L97

I am working around it by handling these events myself.

**Comment by rukai** [comment]
Making the CloseRequested state reset every `WinitInputHelper::step()` is clearly more correct.

However I'm hesitating about splitting up `quit()` into multiple methods.

Say for the simple use case where closing the window should quit immediately without user confirmation.
Then checking both CloseRequested and Destroyed brings a lot of value, as the quit logic will run regardless of if the user requested it or the OS just decided to terminate the window (does that actually happen? from a quick look at the winit implementation it seems possible). 
I think the vast majority of winit-input-helper use cases fall under this, as anything more complicated probably wants to reimplement winit-input-helper level logic in their own way.

That said, if we can add a little extra complexity to support use cases like yours then it might be worth it.
I think if we at least do  `input.close_requested() && input.window_destroyed()` in our example that will lead users to copy in the robust solution.
I'll go ahead and implement it this way.

**Comment by rukai** [comment]
The changes are now on main.
Due to a breaking change already on the main branch I'll be waiting for the next winit release until this actually ends up in a release.
In the mean time you can stick with your work around or if you really want to you can use the git dep.

**Comment by parasyte** [comment]
That sounds like an ok compromise. I didn't have any specific implementations in mind when I reported this. Just happened to recognize the `quit` method was very hard to use for close request use cases.

Thank you for quickly finding a solution that you are happy with.
