### ISSUE TITLE
New release for winit 0.28 support?

### ISSUE THREAD

**Issue by parasyte** [rukai/winit_input_helper#27]
Since #26 was merged a few days ago, can we get a new release? I don't know if there is anything else worth including at this time.

**Comment by rukai** [comment]
yeah, theres nothing blocking it, I'll do one now, in future feel free to make a PR that bumps winit_input_helpers version to prompt me to make a release happen

**Comment by rukai** [comment]
reopening because the publish failed, no idea whats going on
![image](https://user-images.githubusercontent.com/5120858/220511745-e456e3b6-f54f-4800-8fd6-49c65d25deb7.png)

**Comment by parasyte** [comment]
The only thing I can think of is 535e98177942981fe95b0f4670d43918200ee88c?

I have been using 9b9a34459fc121dfd542e728df76a1798a9abf34 on Windows successfully.

**Comment by rukai** [comment]
yep, I think your right!
https://github.com/rukai/winit_input_helper/commit/535e98177942981fe95b0f4670d43918200ee88c does seem to be the culprit
I'll try to figure out a magic incantation to enable winit's features while doing a cargo publish
