### ISSUE TITLE
`input.mouse` does not return `None` outside the window

### ISSUE THREAD

**Issue by Zstorm999** [rukai/winit_input_helper#36]
When dragging the mouse, and checking its position in the code with `input.mouse_held(...)` and `input.mouse()`, the position is not reported as `None` even when the cursor is dragged outside the window. Instead, I get a negative or out of bounds position.

Here is a minimal working example : 
```Rust
use winit::event_loop::EventLoop;
use winit::window::WindowBuilder;
use winit_input_helper::WinitInputHelper;

fn main() {
    let mut input = WinitInputHelper::new();

    let event_loop = EventLoop::new();
    let _window = WindowBuilder::new().build(&event_loop).unwrap();

    event_loop.run(move |event, _, _| {
        if input.update(&event) {
            if input.mouse_held(0) {
                println!("mouse at {:?}", input.mouse())
            }
        }
    });
}
```
This can return for example (when dragging cursor to the left of the window)
```
mouse at Some((-43.0, 517.0))
```

I’m currently on Windows 10, maybe this doesn’t apply to other operating systems/window managers.

From the documentation of `input.mouse`, I would expect this to return `None` when the mouse is outside the window. This could be fixed by using `WindowEvent::CursorEntered` and `WindowEvent::CursorLeft` events to keep track of the mouse being on the window.

**Comment by rukai** [comment]
Sorry about the delay, I've resolved this in https://github.com/rukai/winit_input_helper/pull/45
