### ISSUE TITLE
Could not compile 0.4.0-alpha6 on Windows (Rust 1.40.0)

### ISSUE THREAD

**Issue by spencerelliott** [rukai/winit_input_helper#4]
When running `cargo build` on my Windows 10 computer [for my project](https://github.com/spencerelliott/tinyrenderer-rs) using Rust 1.40.0, I am receiving the following error:
```
   Compiling winit_input_helper v0.4.0-alpha6
   Compiling wgpu-native v0.4.2
error[E0106]: missing lifetime specifier
  --> \.cargo\registry\src\github.com-1ecc6299db9ec823\winit_input_helper-0.4.0-alpha6\src\lib.rs:17:25
   |
17 |     events:         Vec<Event<T>>,
   |                         ^^^^^^^^ expected lifetime parameter

error[E0107]: wrong number of type arguments: expected 1, found 0
  --> \.cargo\registry\src\github.com-1ecc6299db9ec823\winit_input_helper-0.4.0-alpha6\src\lib.rs:14:28
   |
14 |     window_resized: Option<LogicalSize>,
   |                            ^^^^^^^^^^^ expected 1 type argument

error[E0107]: wrong number of type arguments: expected 1, found 0
   --> \.cargo\registry\src\github.com-1ecc6299db9ec823\winit_input_helper-0.4.0-alpha6\src\lib.rs:246:44
    |
246 |     pub fn window_resized(&self) -> Option<LogicalSize> {
    |                                            ^^^^^^^^^^^ expected 1 type argument

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0106, E0107.
For more information about an error, try `rustc --explain E0106`.
error: could not compile `winit_input_helper`.
```

Rustup output:
```
stable-x86_64-pc-windows-msvc (default)
rustc 1.40.0 (73528e339 2019-12-16)
```

The same code works on a Mac running Catalina and Rust 1.40.0.

**Comment by rukai** [comment]
Make sure your project is using winit 0.20.0alpha6. I saw some issues recently where rust wasn't properly following semver for alpha releases.

Regardless I'll update winit_input_helper to winit 0.20.0, tonight after work, which will fix such issues anyway.

**Comment by spencerelliott** [comment]
Yeah, I'm noticing that Rust isn't following the alpha semver at all.
Thanks for the quick reply!

**Comment by rukai** [comment]
0.4.0 is released, try it out.
The upgrade was more involved than I thought it would be, so I didnt end up having the energy to do it during the week.

**Comment by spencerelliott** [comment]
Thanks! No problem. I quickly tried to patch it locally and use that and had it working. I'm new to Rust, though l so I reverted back and just waited for your patch. I'll try it again.
