### ISSUE TITLE
Pairing with glutin and glium

### ISSUE THREAD

**Issue by adrylain** [rukai/winit_input_helper#6]
Trying to use this package with a glutin/glium spawned "Event" struct produces an error.

"^^^^^^ expected enum `winit::event::Event`, found enum `glium::glutin::event::Event`"

This is seemingly because winit_input_helper currently uses winit 0.22.2 as a dependency. Is it likely for this to be the problem, and if so can I even revert winit_input_helper's winit version through cargo.toml?

**Comment by rukai** [comment]
Are you using glutin 0.24 and winit_input_helper 0.7? Because that should work fine as they use the same winit version.

**Comment by adrylain** [comment]
Sadly, the newest version of glium uses glutin 0.23. Sounds like I'll have to hound the glium developers to update their dependencies. ;) Thanks.

**Comment by adrylain** [comment]
As a quick fix for anyone reading this with the same problem, I downgraded to **winit_input_helper 0.5** and it works fine.

**Comment by rukai** [comment]
On crates.io it looks like it says it uses 0.24 https://crates.io/crates/glium
